[[headers]]
  for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"
  for = "/"
  [headers.values]
  Access-Control-Allow-Origin = "*"
  for = "/.next/"
  [headers.values]
  Access-Control-Allow-Origin = "*"